const WA={m:"263719519301",b:"263788678472"};
const $=s=>document.querySelector(s),app=$("#app");
const e=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let D={vehicles:[],meta:{}};
const nav=["Live Stock","Source a Vehicle","How It Works","About","Contact"],slug=n=>n.toLowerCase().replace(/ /g,"-");
const cls=s=>e(s.replace(" ","-"));
const wa=(n,t)=>`https://wa.me/${n}?text=${encodeURIComponent(t)}`;
const ph=v=>v.image?`<img loading="lazy" src="${e(v.image)}" alt="${e(v.year+" "+v.make+" "+v.model)}">`:"PHOTO TO BE ADDED";
const card=v=>`<a class="card" href="#/vehicle/${e(v.id)}"><div class="ph">${ph(v)}</div><div class="b"><span class="st ${cls(v.status)}">${e(v.status)}</span><h3>${e(v.make)} ${e(v.model)}</h3><div class="meta">${e(v.year)} · ${e(v.body)} · ${e(v.power)} · ${e(v.trans)}</div><div class="meta">Updated ${e(v.updated)}</div></div></a>`;
const H=t=>`<h1 style="font-size:clamp(36px,7vw,88px)">${t}</h1>`;
const R={
"":()=>`<section class="hero"><h1>Engineered movement.<br>Sourced with control.</h1><p>AXIS connects customers with vehicles through sourcing and automotive services. Tell us what you need, or see what is moving through our stock.</p><div class="btns"><a class="btn p" href="#/live-stock">VIEW LIVE STOCK</a><a class="btn" href="#/source-a-vehicle">REQUEST A VEHICLE</a></div></section><section><h2>Held, moving, or sourced on request.</h2><p>Every vehicle carries an honest status, so you always know whether it is physically available or still being sourced.</p></section>`,
"live-stock":()=>{const f=k=>[...new Set(D.vehicles.map(v=>v[k]))].map(x=>`<option>${e(x)}</option>`).join("");
return `<section>${H("Live Stock")}<p id="cnt"></p><div class="bar"><label>Status<select id="fs"><option value="">All</option>${["AVAILABLE","IN TRANSIT","ARRIVING","RESERVED","SOLD","SOURCING"].map(s=>`<option>${s}</option>`).join("")}</select></label><label>Body<select id="fb"><option value="">All</option>${f("body")}</select></label><label>Powertrain<select id="fp"><option value="">All</option>${f("power")}</select></label><label>Sort<select id="so"><option value="u">Recently updated</option><option value="y">Year, newest</option></select></label></div><div class="grid" id="lst"></div><p>Stock loads from a static data file and changes when the site is updated. It is not a real-time feed.</p></section>`},
"vehicle":id=>{const v=D.vehicles.find(x=>x.id===id);if(!v)return `<section>${H("Vehicle not found")}<a class="btn" href="#/live-stock">BACK TO LIVE STOCK</a></section>`;
const n=`${v.year} ${v.make} ${v.model}`;document.title=n+" | AXIS Automotive Group";
return `<section><div class="ph" style="aspect-ratio:21/9;margin-bottom:32px">${ph(v)}</div><span class="st ${cls(v.status)}">${e(v.status)}</span><h1 style="font-size:clamp(32px,6vw,72px)">${e(v.make)} ${e(v.model)}</h1><p>${e(v.desc)}</p><dl><dt>Year</dt><dd>${e(v.year)}</dd><dt>Body</dt><dd>${e(v.body)}</dd><dt>Powertrain</dt><dd>${e(v.power)}</dd><dt>Transmission</dt><dd>${e(v.trans)}</dd><dt>Mileage</dt><dd>${e(v.mileage)}</dd><dt>Location</dt><dd>${e(v.location)}</dd><dt>Last updated</dt><dd>${e(v.updated)}</dd></dl><div class="btns"><a class="btn p" href="${wa(WA.b,"Hello AXIS, I would like to request: "+n+" ("+v.id+")")}" rel="noopener">REQUEST THIS VEHICLE</a><a class="btn" href="#/contact">CONTACT OUR TEAM</a></div></section>`},
"source-a-vehicle":()=>`<section>${H("Source a vehicle")}<p>Tell us what you are looking for. This starts a conversation. It does not purchase a vehicle.</p><form id="sf"><div class="two"><label>Name<input name="Name" required autocomplete="name"></label><label>WhatsApp / Phone<input name="Phone" type="tel" required autocomplete="tel"></label></div><label>Email<input name="Email" type="email" autocomplete="email"></label><div class="two"><label>Manufacturer<input name="Manufacturer"></label><label>Model<input name="Model"></label></div><div class="two"><label>Year<input name="Year" inputmode="numeric"></label><label>Budget<input name="Budget"></label></div><div class="two"><label>Vehicle type<input name="Vehicle type"></label><label>Fuel / powertrain<select name="Powertrain"><option>Any</option><option>Petrol</option><option>Diesel</option><option>Hybrid</option><option>Electric</option></select></label></div><label>Transmission<select name="Transmission"><option>Any</option><option>Automatic</option><option>Manual</option></select></label><label>Additional requirements<textarea name="Notes" rows="4"></textarea></label><button class="btn p" type="submit">START THE CONVERSATION</button><p>Submitting opens WhatsApp with your details pre-filled. This website stores nothing.</p></form></section>`,
"how-it-works":()=>`<section>${H("How it works")}<ol class="steps"><li>Tell us what you want.</li><li>We identify suitable vehicles.</li><li>Vehicle information is reviewed.</li><li>Sourcing and import details are discussed.</li><li>The process is coordinated.</li><li>The vehicle is delivered through the agreed process.</li></ol><p>Terms, costs, timelines and requirements are agreed directly with AXIS for each vehicle.</p></section>`,
"about":()=>`<section>${H("About AXIS")}<p>AXIS Automotive Group is a young company with a long-term automotive vision: sourcing and importing first, with a wider automotive group to be built over time.</p></section><section class="cols"><div><h2>Metatron878</h2><p>Tawananyasha Nzombe<br>Technical &amp; Digital Operations</p></div><div><h2>Billionaire Sukhs</h2><p>Angel Rubaya<br>Business &amp; Strategic Operations</p></div></section>`,
"contact":()=>`<section>${H("Contact")}<div class="cols"><div><h3>Metatron878</h3><p>Technical &amp; Digital Operations</p><div class="btns"><a class="btn p" href="${wa(WA.m,"Hello AXIS")}" rel="noopener">WHATSAPP</a><a class="btn" href="tel:+263719519301">CALL +263 71 951 9301</a></div></div><div><h3>Billionaire Sukhs</h3><p>Business &amp; Strategic Operations</p><div class="btns"><a class="btn p" href="${wa(WA.b,"Hello AXIS")}" rel="noopener">WHATSAPP</a><a class="btn" href="tel:+263788678472">CALL +263 78 867 8472</a></div></div></div><p>Company email to be announced.</p></section>`};
function list(){const g=i=>$(i).value;const r=D.vehicles.filter(v=>(!g("#fs")||v.status===g("#fs"))&&(!g("#fb")||v.body===g("#fb"))&&(!g("#fp")||v.power===g("#fp")));
r.sort(g("#so")==="y"?(a,b)=>b.year-a.year:(a,b)=>b.updated.localeCompare(a.updated));
$("#lst").innerHTML=r.map(card).join("")||"<p style='padding:20px'>No vehicles match these filters. Clear a filter or request a vehicle.</p>";
$("#cnt").textContent=`${D.vehicles.length} listed, ${D.vehicles.filter(v=>v.status==="AVAILABLE").length} physically available. Data updated ${D.meta.updated}.`}
function route(){const p=location.hash.replace(/^#\/?/,"").split("/"),k=p[0],fn=R[k]||R[""];
const t=nav.find(n=>slug(n)===k);document.title=(t?t+" | ":"")+"AXIS Automotive Group";
app.innerHTML=fn(p[1]);window.scrollTo(0,0);
document.querySelectorAll("nav a").forEach(a=>a.toggleAttribute("aria-current",a.getAttribute("href")==="#/"+k));
if(k==="live-stock"){list();document.querySelectorAll(".bar select").forEach(s=>s.onchange=list)}
const f=$("#sf");if(f)f.onsubmit=ev=>{ev.preventDefault();let t="AXIS vehicle request:\n";new FormData(f).forEach((v,k)=>{if(v)t+=k+": "+v+"\n"});open(wa(WA.b,t),"_blank","noopener")}}
$("#nav").innerHTML=nav.map(n=>`<a href="#/${slug(n)}">${n}</a>`).join("");
fetch("data/stock.json").then(r=>r.json()).then(d=>{D=d;$("#demo").hidden=!d.meta.demo}).catch(()=>{}).finally(route);
addEventListener("hashchange",route);
